// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.cl.java.serialization.compare;

public final class Products2 {
  private Products2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Products22OrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Products22)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string s1 = 1;</code>
     */
    boolean hasS1();
    /**
     * <code>required string s1 = 1;</code>
     */
    java.lang.String getS1();
    /**
     * <code>required string s1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getS1Bytes();

    /**
     * <code>required string s2 = 2;</code>
     */
    boolean hasS2();
    /**
     * <code>required string s2 = 2;</code>
     */
    java.lang.String getS2();
    /**
     * <code>required string s2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getS2Bytes();

    /**
     * <code>required string s3 = 3;</code>
     */
    boolean hasS3();
    /**
     * <code>required string s3 = 3;</code>
     */
    java.lang.String getS3();
    /**
     * <code>required string s3 = 3;</code>
     */
    com.google.protobuf.ByteString
        getS3Bytes();

    /**
     * <code>required string s4 = 4;</code>
     */
    boolean hasS4();
    /**
     * <code>required string s4 = 4;</code>
     */
    java.lang.String getS4();
    /**
     * <code>required string s4 = 4;</code>
     */
    com.google.protobuf.ByteString
        getS4Bytes();

    /**
     * <code>required string s5 = 5;</code>
     */
    boolean hasS5();
    /**
     * <code>required string s5 = 5;</code>
     */
    java.lang.String getS5();
    /**
     * <code>required string s5 = 5;</code>
     */
    com.google.protobuf.ByteString
        getS5Bytes();

    /**
     * <code>required string s6 = 6;</code>
     */
    boolean hasS6();
    /**
     * <code>required string s6 = 6;</code>
     */
    java.lang.String getS6();
    /**
     * <code>required string s6 = 6;</code>
     */
    com.google.protobuf.ByteString
        getS6Bytes();

    /**
     * <code>required string s7 = 7;</code>
     */
    boolean hasS7();
    /**
     * <code>required string s7 = 7;</code>
     */
    java.lang.String getS7();
    /**
     * <code>required string s7 = 7;</code>
     */
    com.google.protobuf.ByteString
        getS7Bytes();

    /**
     * <code>required string s8 = 8;</code>
     */
    boolean hasS8();
    /**
     * <code>required string s8 = 8;</code>
     */
    java.lang.String getS8();
    /**
     * <code>required string s8 = 8;</code>
     */
    com.google.protobuf.ByteString
        getS8Bytes();

    /**
     * <code>required string s9 = 9;</code>
     */
    boolean hasS9();
    /**
     * <code>required string s9 = 9;</code>
     */
    java.lang.String getS9();
    /**
     * <code>required string s9 = 9;</code>
     */
    com.google.protobuf.ByteString
        getS9Bytes();

    /**
     * <code>required int32 i10 = 10;</code>
     */
    boolean hasI10();
    /**
     * <code>required int32 i10 = 10;</code>
     */
    int getI10();

    /**
     * <code>required int32 i11 = 11;</code>
     */
    boolean hasI11();
    /**
     * <code>required int32 i11 = 11;</code>
     */
    int getI11();

    /**
     * <code>required int32 i12 = 12;</code>
     */
    boolean hasI12();
    /**
     * <code>required int32 i12 = 12;</code>
     */
    int getI12();

    /**
     * <code>required int32 i13 = 13;</code>
     */
    boolean hasI13();
    /**
     * <code>required int32 i13 = 13;</code>
     */
    int getI13();

    /**
     * <code>required int32 i14 = 14;</code>
     */
    boolean hasI14();
    /**
     * <code>required int32 i14 = 14;</code>
     */
    int getI14();

    /**
     * <code>required int32 i15 = 15;</code>
     */
    boolean hasI15();
    /**
     * <code>required int32 i15 = 15;</code>
     */
    int getI15();

    /**
     * <code>required int32 i16 = 16;</code>
     */
    boolean hasI16();
    /**
     * <code>required int32 i16 = 16;</code>
     */
    int getI16();

    /**
     * <code>required int32 i17 = 17;</code>
     */
    boolean hasI17();
    /**
     * <code>required int32 i17 = 17;</code>
     */
    int getI17();

    /**
     * <code>required int32 i18 = 18;</code>
     */
    boolean hasI18();
    /**
     * <code>required int32 i18 = 18;</code>
     */
    int getI18();

    /**
     * <code>required bool b19 = 19;</code>
     */
    boolean hasB19();
    /**
     * <code>required bool b19 = 19;</code>
     */
    boolean getB19();

    /**
     * <code>required bool b20 = 20;</code>
     */
    boolean hasB20();
    /**
     * <code>required bool b20 = 20;</code>
     */
    boolean getB20();

    /**
     * <code>required bool b21 = 21;</code>
     */
    boolean hasB21();
    /**
     * <code>required bool b21 = 21;</code>
     */
    boolean getB21();

    /**
     * <code>required bool b22 = 22;</code>
     */
    boolean hasB22();
    /**
     * <code>required bool b22 = 22;</code>
     */
    boolean getB22();

    /**
     * <code>required bool b23 = 23;</code>
     */
    boolean hasB23();
    /**
     * <code>required bool b23 = 23;</code>
     */
    boolean getB23();

    /**
     * <code>required bool b24 = 24;</code>
     */
    boolean hasB24();
    /**
     * <code>required bool b24 = 24;</code>
     */
    boolean getB24();

    /**
     * <code>required bool b25 = 25;</code>
     */
    boolean hasB25();
    /**
     * <code>required bool b25 = 25;</code>
     */
    boolean getB25();

    /**
     * <code>required bool b26 = 26;</code>
     */
    boolean hasB26();
    /**
     * <code>required bool b26 = 26;</code>
     */
    boolean getB26();

    /**
     * <code>required bool b27 = 27;</code>
     */
    boolean hasB27();
    /**
     * <code>required bool b27 = 27;</code>
     */
    boolean getB27();

    /**
     * <code>repeated string list = 28;</code>
     */
    com.google.protobuf.ProtocolStringList
        getListList();
    /**
     * <code>repeated string list = 28;</code>
     */
    int getListCount();
    /**
     * <code>repeated string list = 28;</code>
     */
    java.lang.String getList(int index);
    /**
     * <code>repeated string list = 28;</code>
     */
    com.google.protobuf.ByteString
        getListBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.Products22}
   */
  public  static final class Products22 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.Products22)
      Products22OrBuilder {
    // Use Products22.newBuilder() to construct.
    private Products22(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Products22() {
      s1_ = "";
      s2_ = "";
      s3_ = "";
      s4_ = "";
      s5_ = "";
      s6_ = "";
      s7_ = "";
      s8_ = "";
      s9_ = "";
      i10_ = 0;
      i11_ = 0;
      i12_ = 0;
      i13_ = 0;
      i14_ = 0;
      i15_ = 0;
      i16_ = 0;
      i17_ = 0;
      i18_ = 0;
      b19_ = false;
      b20_ = false;
      b21_ = false;
      b22_ = false;
      b23_ = false;
      b24_ = false;
      b25_ = false;
      b26_ = false;
      b27_ = false;
      list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Products22(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              s1_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              s2_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              s3_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              s4_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              s5_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              s6_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              s7_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              s8_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              s9_ = bs;
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              i10_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              i11_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              i12_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              i13_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              i14_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              i15_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              i16_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              i17_ = input.readInt32();
              break;
            }
            case 144: {
              bitField0_ |= 0x00020000;
              i18_ = input.readInt32();
              break;
            }
            case 152: {
              bitField0_ |= 0x00040000;
              b19_ = input.readBool();
              break;
            }
            case 160: {
              bitField0_ |= 0x00080000;
              b20_ = input.readBool();
              break;
            }
            case 168: {
              bitField0_ |= 0x00100000;
              b21_ = input.readBool();
              break;
            }
            case 176: {
              bitField0_ |= 0x00200000;
              b22_ = input.readBool();
              break;
            }
            case 184: {
              bitField0_ |= 0x00400000;
              b23_ = input.readBool();
              break;
            }
            case 192: {
              bitField0_ |= 0x00800000;
              b24_ = input.readBool();
              break;
            }
            case 200: {
              bitField0_ |= 0x01000000;
              b25_ = input.readBool();
              break;
            }
            case 208: {
              bitField0_ |= 0x02000000;
              b26_ = input.readBool();
              break;
            }
            case 216: {
              bitField0_ |= 0x04000000;
              b27_ = input.readBool();
              break;
            }
            case 226: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x08000000) == 0x08000000)) {
                list_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x08000000;
              }
              list_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x08000000) == 0x08000000)) {
          list_ = list_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cl.java.serialization.compare.Products2.internal_static_tutorial_Products22_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cl.java.serialization.compare.Products2.internal_static_tutorial_Products22_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cl.java.serialization.compare.Products2.Products22.class, com.cl.java.serialization.compare.Products2.Products22.Builder.class);
    }

    public static final com.google.protobuf.Parser<Products22> PARSER =
        new com.google.protobuf.AbstractParser<Products22>() {
      public Products22 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Products22(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Products22> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int S1_FIELD_NUMBER = 1;
    private java.lang.Object s1_;
    /**
     * <code>required string s1 = 1;</code>
     */
    public boolean hasS1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string s1 = 1;</code>
     */
    public java.lang.String getS1() {
      java.lang.Object ref = s1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getS1Bytes() {
      java.lang.Object ref = s1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S2_FIELD_NUMBER = 2;
    private java.lang.Object s2_;
    /**
     * <code>required string s2 = 2;</code>
     */
    public boolean hasS2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string s2 = 2;</code>
     */
    public java.lang.String getS2() {
      java.lang.Object ref = s2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getS2Bytes() {
      java.lang.Object ref = s2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S3_FIELD_NUMBER = 3;
    private java.lang.Object s3_;
    /**
     * <code>required string s3 = 3;</code>
     */
    public boolean hasS3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string s3 = 3;</code>
     */
    public java.lang.String getS3() {
      java.lang.Object ref = s3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getS3Bytes() {
      java.lang.Object ref = s3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S4_FIELD_NUMBER = 4;
    private java.lang.Object s4_;
    /**
     * <code>required string s4 = 4;</code>
     */
    public boolean hasS4() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string s4 = 4;</code>
     */
    public java.lang.String getS4() {
      java.lang.Object ref = s4_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s4_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s4 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getS4Bytes() {
      java.lang.Object ref = s4_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S5_FIELD_NUMBER = 5;
    private java.lang.Object s5_;
    /**
     * <code>required string s5 = 5;</code>
     */
    public boolean hasS5() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string s5 = 5;</code>
     */
    public java.lang.String getS5() {
      java.lang.Object ref = s5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s5_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s5 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getS5Bytes() {
      java.lang.Object ref = s5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S6_FIELD_NUMBER = 6;
    private java.lang.Object s6_;
    /**
     * <code>required string s6 = 6;</code>
     */
    public boolean hasS6() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string s6 = 6;</code>
     */
    public java.lang.String getS6() {
      java.lang.Object ref = s6_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s6_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s6 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getS6Bytes() {
      java.lang.Object ref = s6_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s6_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S7_FIELD_NUMBER = 7;
    private java.lang.Object s7_;
    /**
     * <code>required string s7 = 7;</code>
     */
    public boolean hasS7() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string s7 = 7;</code>
     */
    public java.lang.String getS7() {
      java.lang.Object ref = s7_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s7_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s7 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getS7Bytes() {
      java.lang.Object ref = s7_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s7_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S8_FIELD_NUMBER = 8;
    private java.lang.Object s8_;
    /**
     * <code>required string s8 = 8;</code>
     */
    public boolean hasS8() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string s8 = 8;</code>
     */
    public java.lang.String getS8() {
      java.lang.Object ref = s8_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s8_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s8 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getS8Bytes() {
      java.lang.Object ref = s8_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s8_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S9_FIELD_NUMBER = 9;
    private java.lang.Object s9_;
    /**
     * <code>required string s9 = 9;</code>
     */
    public boolean hasS9() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string s9 = 9;</code>
     */
    public java.lang.String getS9() {
      java.lang.Object ref = s9_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s9_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string s9 = 9;</code>
     */
    public com.google.protobuf.ByteString
        getS9Bytes() {
      java.lang.Object ref = s9_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s9_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int I10_FIELD_NUMBER = 10;
    private int i10_;
    /**
     * <code>required int32 i10 = 10;</code>
     */
    public boolean hasI10() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int32 i10 = 10;</code>
     */
    public int getI10() {
      return i10_;
    }

    public static final int I11_FIELD_NUMBER = 11;
    private int i11_;
    /**
     * <code>required int32 i11 = 11;</code>
     */
    public boolean hasI11() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int32 i11 = 11;</code>
     */
    public int getI11() {
      return i11_;
    }

    public static final int I12_FIELD_NUMBER = 12;
    private int i12_;
    /**
     * <code>required int32 i12 = 12;</code>
     */
    public boolean hasI12() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int32 i12 = 12;</code>
     */
    public int getI12() {
      return i12_;
    }

    public static final int I13_FIELD_NUMBER = 13;
    private int i13_;
    /**
     * <code>required int32 i13 = 13;</code>
     */
    public boolean hasI13() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required int32 i13 = 13;</code>
     */
    public int getI13() {
      return i13_;
    }

    public static final int I14_FIELD_NUMBER = 14;
    private int i14_;
    /**
     * <code>required int32 i14 = 14;</code>
     */
    public boolean hasI14() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required int32 i14 = 14;</code>
     */
    public int getI14() {
      return i14_;
    }

    public static final int I15_FIELD_NUMBER = 15;
    private int i15_;
    /**
     * <code>required int32 i15 = 15;</code>
     */
    public boolean hasI15() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>required int32 i15 = 15;</code>
     */
    public int getI15() {
      return i15_;
    }

    public static final int I16_FIELD_NUMBER = 16;
    private int i16_;
    /**
     * <code>required int32 i16 = 16;</code>
     */
    public boolean hasI16() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>required int32 i16 = 16;</code>
     */
    public int getI16() {
      return i16_;
    }

    public static final int I17_FIELD_NUMBER = 17;
    private int i17_;
    /**
     * <code>required int32 i17 = 17;</code>
     */
    public boolean hasI17() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>required int32 i17 = 17;</code>
     */
    public int getI17() {
      return i17_;
    }

    public static final int I18_FIELD_NUMBER = 18;
    private int i18_;
    /**
     * <code>required int32 i18 = 18;</code>
     */
    public boolean hasI18() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <code>required int32 i18 = 18;</code>
     */
    public int getI18() {
      return i18_;
    }

    public static final int B19_FIELD_NUMBER = 19;
    private boolean b19_;
    /**
     * <code>required bool b19 = 19;</code>
     */
    public boolean hasB19() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <code>required bool b19 = 19;</code>
     */
    public boolean getB19() {
      return b19_;
    }

    public static final int B20_FIELD_NUMBER = 20;
    private boolean b20_;
    /**
     * <code>required bool b20 = 20;</code>
     */
    public boolean hasB20() {
      return ((bitField0_ & 0x00080000) == 0x00080000);
    }
    /**
     * <code>required bool b20 = 20;</code>
     */
    public boolean getB20() {
      return b20_;
    }

    public static final int B21_FIELD_NUMBER = 21;
    private boolean b21_;
    /**
     * <code>required bool b21 = 21;</code>
     */
    public boolean hasB21() {
      return ((bitField0_ & 0x00100000) == 0x00100000);
    }
    /**
     * <code>required bool b21 = 21;</code>
     */
    public boolean getB21() {
      return b21_;
    }

    public static final int B22_FIELD_NUMBER = 22;
    private boolean b22_;
    /**
     * <code>required bool b22 = 22;</code>
     */
    public boolean hasB22() {
      return ((bitField0_ & 0x00200000) == 0x00200000);
    }
    /**
     * <code>required bool b22 = 22;</code>
     */
    public boolean getB22() {
      return b22_;
    }

    public static final int B23_FIELD_NUMBER = 23;
    private boolean b23_;
    /**
     * <code>required bool b23 = 23;</code>
     */
    public boolean hasB23() {
      return ((bitField0_ & 0x00400000) == 0x00400000);
    }
    /**
     * <code>required bool b23 = 23;</code>
     */
    public boolean getB23() {
      return b23_;
    }

    public static final int B24_FIELD_NUMBER = 24;
    private boolean b24_;
    /**
     * <code>required bool b24 = 24;</code>
     */
    public boolean hasB24() {
      return ((bitField0_ & 0x00800000) == 0x00800000);
    }
    /**
     * <code>required bool b24 = 24;</code>
     */
    public boolean getB24() {
      return b24_;
    }

    public static final int B25_FIELD_NUMBER = 25;
    private boolean b25_;
    /**
     * <code>required bool b25 = 25;</code>
     */
    public boolean hasB25() {
      return ((bitField0_ & 0x01000000) == 0x01000000);
    }
    /**
     * <code>required bool b25 = 25;</code>
     */
    public boolean getB25() {
      return b25_;
    }

    public static final int B26_FIELD_NUMBER = 26;
    private boolean b26_;
    /**
     * <code>required bool b26 = 26;</code>
     */
    public boolean hasB26() {
      return ((bitField0_ & 0x02000000) == 0x02000000);
    }
    /**
     * <code>required bool b26 = 26;</code>
     */
    public boolean getB26() {
      return b26_;
    }

    public static final int B27_FIELD_NUMBER = 27;
    private boolean b27_;
    /**
     * <code>required bool b27 = 27;</code>
     */
    public boolean hasB27() {
      return ((bitField0_ & 0x04000000) == 0x04000000);
    }
    /**
     * <code>required bool b27 = 27;</code>
     */
    public boolean getB27() {
      return b27_;
    }

    public static final int LIST_FIELD_NUMBER = 28;
    private com.google.protobuf.LazyStringList list_;
    /**
     * <code>repeated string list = 28;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getListList() {
      return list_;
    }
    /**
     * <code>repeated string list = 28;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated string list = 28;</code>
     */
    public java.lang.String getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated string list = 28;</code>
     */
    public com.google.protobuf.ByteString
        getListBytes(int index) {
      return list_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasS1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS4()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS5()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS6()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS7()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS8()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS9()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasI10()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasI11()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasI12()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasI13()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasI14()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasI15()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasI16()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasI17()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasI18()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasB19()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasB20()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasB21()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasB22()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasB23()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasB24()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasB25()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasB26()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasB27()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getS1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getS2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getS3Bytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getS4Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getS5Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getS6Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getS7Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getS8Bytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getS9Bytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, i10_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, i11_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, i12_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, i13_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, i14_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, i15_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(16, i16_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeInt32(17, i17_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeInt32(18, i18_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeBool(19, b19_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        output.writeBool(20, b20_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        output.writeBool(21, b21_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        output.writeBool(22, b22_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        output.writeBool(23, b23_);
      }
      if (((bitField0_ & 0x00800000) == 0x00800000)) {
        output.writeBool(24, b24_);
      }
      if (((bitField0_ & 0x01000000) == 0x01000000)) {
        output.writeBool(25, b25_);
      }
      if (((bitField0_ & 0x02000000) == 0x02000000)) {
        output.writeBool(26, b26_);
      }
      if (((bitField0_ & 0x04000000) == 0x04000000)) {
        output.writeBool(27, b27_);
      }
      for (int i = 0; i < list_.size(); i++) {
        output.writeBytes(28, list_.getByteString(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getS1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getS2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getS3Bytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getS4Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getS5Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getS6Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getS7Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getS8Bytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getS9Bytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, i10_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, i11_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, i12_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, i13_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, i14_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, i15_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, i16_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, i17_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, i18_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(19, b19_);
      }
      if (((bitField0_ & 0x00080000) == 0x00080000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(20, b20_);
      }
      if (((bitField0_ & 0x00100000) == 0x00100000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(21, b21_);
      }
      if (((bitField0_ & 0x00200000) == 0x00200000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(22, b22_);
      }
      if (((bitField0_ & 0x00400000) == 0x00400000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(23, b23_);
      }
      if (((bitField0_ & 0x00800000) == 0x00800000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(24, b24_);
      }
      if (((bitField0_ & 0x01000000) == 0x01000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(25, b25_);
      }
      if (((bitField0_ & 0x02000000) == 0x02000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(26, b26_);
      }
      if (((bitField0_ & 0x04000000) == 0x04000000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(27, b27_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < list_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(list_.getByteString(i));
        }
        size += dataSize;
        size += 2 * getListList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.cl.java.serialization.compare.Products2.Products22 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cl.java.serialization.compare.Products2.Products22 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cl.java.serialization.compare.Products2.Products22 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cl.java.serialization.compare.Products2.Products22 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cl.java.serialization.compare.Products2.Products22 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cl.java.serialization.compare.Products2.Products22 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cl.java.serialization.compare.Products2.Products22 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cl.java.serialization.compare.Products2.Products22 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cl.java.serialization.compare.Products2.Products22 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cl.java.serialization.compare.Products2.Products22 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cl.java.serialization.compare.Products2.Products22 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Products22}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Products22)
        com.cl.java.serialization.compare.Products2.Products22OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cl.java.serialization.compare.Products2.internal_static_tutorial_Products22_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cl.java.serialization.compare.Products2.internal_static_tutorial_Products22_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cl.java.serialization.compare.Products2.Products22.class, com.cl.java.serialization.compare.Products2.Products22.Builder.class);
      }

      // Construct using com.cl.java.serialization.compare.Products2.Products22.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        s1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        s2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        s3_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        s4_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        s5_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        s6_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        s7_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        s8_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        s9_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        i10_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        i11_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        i12_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        i13_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        i14_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        i15_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        i16_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        i17_ = 0;
        bitField0_ = (bitField0_ & ~0x00010000);
        i18_ = 0;
        bitField0_ = (bitField0_ & ~0x00020000);
        b19_ = false;
        bitField0_ = (bitField0_ & ~0x00040000);
        b20_ = false;
        bitField0_ = (bitField0_ & ~0x00080000);
        b21_ = false;
        bitField0_ = (bitField0_ & ~0x00100000);
        b22_ = false;
        bitField0_ = (bitField0_ & ~0x00200000);
        b23_ = false;
        bitField0_ = (bitField0_ & ~0x00400000);
        b24_ = false;
        bitField0_ = (bitField0_ & ~0x00800000);
        b25_ = false;
        bitField0_ = (bitField0_ & ~0x01000000);
        b26_ = false;
        bitField0_ = (bitField0_ & ~0x02000000);
        b27_ = false;
        bitField0_ = (bitField0_ & ~0x04000000);
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x08000000);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cl.java.serialization.compare.Products2.internal_static_tutorial_Products22_descriptor;
      }

      public com.cl.java.serialization.compare.Products2.Products22 getDefaultInstanceForType() {
        return com.cl.java.serialization.compare.Products2.Products22.getDefaultInstance();
      }

      public com.cl.java.serialization.compare.Products2.Products22 build() {
        com.cl.java.serialization.compare.Products2.Products22 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cl.java.serialization.compare.Products2.Products22 buildPartial() {
        com.cl.java.serialization.compare.Products2.Products22 result = new com.cl.java.serialization.compare.Products2.Products22(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.s1_ = s1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s2_ = s2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.s3_ = s3_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.s4_ = s4_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.s5_ = s5_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.s6_ = s6_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.s7_ = s7_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.s8_ = s8_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.s9_ = s9_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.i10_ = i10_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.i11_ = i11_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.i12_ = i12_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.i13_ = i13_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.i14_ = i14_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.i15_ = i15_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.i16_ = i16_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.i17_ = i17_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.i18_ = i18_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.b19_ = b19_;
        if (((from_bitField0_ & 0x00080000) == 0x00080000)) {
          to_bitField0_ |= 0x00080000;
        }
        result.b20_ = b20_;
        if (((from_bitField0_ & 0x00100000) == 0x00100000)) {
          to_bitField0_ |= 0x00100000;
        }
        result.b21_ = b21_;
        if (((from_bitField0_ & 0x00200000) == 0x00200000)) {
          to_bitField0_ |= 0x00200000;
        }
        result.b22_ = b22_;
        if (((from_bitField0_ & 0x00400000) == 0x00400000)) {
          to_bitField0_ |= 0x00400000;
        }
        result.b23_ = b23_;
        if (((from_bitField0_ & 0x00800000) == 0x00800000)) {
          to_bitField0_ |= 0x00800000;
        }
        result.b24_ = b24_;
        if (((from_bitField0_ & 0x01000000) == 0x01000000)) {
          to_bitField0_ |= 0x01000000;
        }
        result.b25_ = b25_;
        if (((from_bitField0_ & 0x02000000) == 0x02000000)) {
          to_bitField0_ |= 0x02000000;
        }
        result.b26_ = b26_;
        if (((from_bitField0_ & 0x04000000) == 0x04000000)) {
          to_bitField0_ |= 0x04000000;
        }
        result.b27_ = b27_;
        if (((bitField0_ & 0x08000000) == 0x08000000)) {
          list_ = list_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x08000000);
        }
        result.list_ = list_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cl.java.serialization.compare.Products2.Products22) {
          return mergeFrom((com.cl.java.serialization.compare.Products2.Products22)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cl.java.serialization.compare.Products2.Products22 other) {
        if (other == com.cl.java.serialization.compare.Products2.Products22.getDefaultInstance()) return this;
        if (other.hasS1()) {
          bitField0_ |= 0x00000001;
          s1_ = other.s1_;
          onChanged();
        }
        if (other.hasS2()) {
          bitField0_ |= 0x00000002;
          s2_ = other.s2_;
          onChanged();
        }
        if (other.hasS3()) {
          bitField0_ |= 0x00000004;
          s3_ = other.s3_;
          onChanged();
        }
        if (other.hasS4()) {
          bitField0_ |= 0x00000008;
          s4_ = other.s4_;
          onChanged();
        }
        if (other.hasS5()) {
          bitField0_ |= 0x00000010;
          s5_ = other.s5_;
          onChanged();
        }
        if (other.hasS6()) {
          bitField0_ |= 0x00000020;
          s6_ = other.s6_;
          onChanged();
        }
        if (other.hasS7()) {
          bitField0_ |= 0x00000040;
          s7_ = other.s7_;
          onChanged();
        }
        if (other.hasS8()) {
          bitField0_ |= 0x00000080;
          s8_ = other.s8_;
          onChanged();
        }
        if (other.hasS9()) {
          bitField0_ |= 0x00000100;
          s9_ = other.s9_;
          onChanged();
        }
        if (other.hasI10()) {
          setI10(other.getI10());
        }
        if (other.hasI11()) {
          setI11(other.getI11());
        }
        if (other.hasI12()) {
          setI12(other.getI12());
        }
        if (other.hasI13()) {
          setI13(other.getI13());
        }
        if (other.hasI14()) {
          setI14(other.getI14());
        }
        if (other.hasI15()) {
          setI15(other.getI15());
        }
        if (other.hasI16()) {
          setI16(other.getI16());
        }
        if (other.hasI17()) {
          setI17(other.getI17());
        }
        if (other.hasI18()) {
          setI18(other.getI18());
        }
        if (other.hasB19()) {
          setB19(other.getB19());
        }
        if (other.hasB20()) {
          setB20(other.getB20());
        }
        if (other.hasB21()) {
          setB21(other.getB21());
        }
        if (other.hasB22()) {
          setB22(other.getB22());
        }
        if (other.hasB23()) {
          setB23(other.getB23());
        }
        if (other.hasB24()) {
          setB24(other.getB24());
        }
        if (other.hasB25()) {
          setB25(other.getB25());
        }
        if (other.hasB26()) {
          setB26(other.getB26());
        }
        if (other.hasB27()) {
          setB27(other.getB27());
        }
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x08000000);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasS1()) {
          
          return false;
        }
        if (!hasS2()) {
          
          return false;
        }
        if (!hasS3()) {
          
          return false;
        }
        if (!hasS4()) {
          
          return false;
        }
        if (!hasS5()) {
          
          return false;
        }
        if (!hasS6()) {
          
          return false;
        }
        if (!hasS7()) {
          
          return false;
        }
        if (!hasS8()) {
          
          return false;
        }
        if (!hasS9()) {
          
          return false;
        }
        if (!hasI10()) {
          
          return false;
        }
        if (!hasI11()) {
          
          return false;
        }
        if (!hasI12()) {
          
          return false;
        }
        if (!hasI13()) {
          
          return false;
        }
        if (!hasI14()) {
          
          return false;
        }
        if (!hasI15()) {
          
          return false;
        }
        if (!hasI16()) {
          
          return false;
        }
        if (!hasI17()) {
          
          return false;
        }
        if (!hasI18()) {
          
          return false;
        }
        if (!hasB19()) {
          
          return false;
        }
        if (!hasB20()) {
          
          return false;
        }
        if (!hasB21()) {
          
          return false;
        }
        if (!hasB22()) {
          
          return false;
        }
        if (!hasB23()) {
          
          return false;
        }
        if (!hasB24()) {
          
          return false;
        }
        if (!hasB25()) {
          
          return false;
        }
        if (!hasB26()) {
          
          return false;
        }
        if (!hasB27()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cl.java.serialization.compare.Products2.Products22 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cl.java.serialization.compare.Products2.Products22) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object s1_ = "";
      /**
       * <code>required string s1 = 1;</code>
       */
      public boolean hasS1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string s1 = 1;</code>
       */
      public java.lang.String getS1() {
        java.lang.Object ref = s1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getS1Bytes() {
        java.lang.Object ref = s1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s1 = 1;</code>
       */
      public Builder setS1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        s1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s1 = 1;</code>
       */
      public Builder clearS1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        s1_ = getDefaultInstance().getS1();
        onChanged();
        return this;
      }
      /**
       * <code>required string s1 = 1;</code>
       */
      public Builder setS1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        s1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s2_ = "";
      /**
       * <code>required string s2 = 2;</code>
       */
      public boolean hasS2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string s2 = 2;</code>
       */
      public java.lang.String getS2() {
        java.lang.Object ref = s2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getS2Bytes() {
        java.lang.Object ref = s2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s2 = 2;</code>
       */
      public Builder setS2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s2 = 2;</code>
       */
      public Builder clearS2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s2_ = getDefaultInstance().getS2();
        onChanged();
        return this;
      }
      /**
       * <code>required string s2 = 2;</code>
       */
      public Builder setS2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s3_ = "";
      /**
       * <code>required string s3 = 3;</code>
       */
      public boolean hasS3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string s3 = 3;</code>
       */
      public java.lang.String getS3() {
        java.lang.Object ref = s3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s3_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s3 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getS3Bytes() {
        java.lang.Object ref = s3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s3 = 3;</code>
       */
      public Builder setS3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        s3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s3 = 3;</code>
       */
      public Builder clearS3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        s3_ = getDefaultInstance().getS3();
        onChanged();
        return this;
      }
      /**
       * <code>required string s3 = 3;</code>
       */
      public Builder setS3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        s3_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s4_ = "";
      /**
       * <code>required string s4 = 4;</code>
       */
      public boolean hasS4() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string s4 = 4;</code>
       */
      public java.lang.String getS4() {
        java.lang.Object ref = s4_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s4_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s4 = 4;</code>
       */
      public com.google.protobuf.ByteString
          getS4Bytes() {
        java.lang.Object ref = s4_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s4_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s4 = 4;</code>
       */
      public Builder setS4(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        s4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s4 = 4;</code>
       */
      public Builder clearS4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        s4_ = getDefaultInstance().getS4();
        onChanged();
        return this;
      }
      /**
       * <code>required string s4 = 4;</code>
       */
      public Builder setS4Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        s4_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s5_ = "";
      /**
       * <code>required string s5 = 5;</code>
       */
      public boolean hasS5() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string s5 = 5;</code>
       */
      public java.lang.String getS5() {
        java.lang.Object ref = s5_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s5_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s5 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getS5Bytes() {
        java.lang.Object ref = s5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s5 = 5;</code>
       */
      public Builder setS5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        s5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s5 = 5;</code>
       */
      public Builder clearS5() {
        bitField0_ = (bitField0_ & ~0x00000010);
        s5_ = getDefaultInstance().getS5();
        onChanged();
        return this;
      }
      /**
       * <code>required string s5 = 5;</code>
       */
      public Builder setS5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        s5_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s6_ = "";
      /**
       * <code>required string s6 = 6;</code>
       */
      public boolean hasS6() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string s6 = 6;</code>
       */
      public java.lang.String getS6() {
        java.lang.Object ref = s6_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s6_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s6 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getS6Bytes() {
        java.lang.Object ref = s6_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s6_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s6 = 6;</code>
       */
      public Builder setS6(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        s6_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s6 = 6;</code>
       */
      public Builder clearS6() {
        bitField0_ = (bitField0_ & ~0x00000020);
        s6_ = getDefaultInstance().getS6();
        onChanged();
        return this;
      }
      /**
       * <code>required string s6 = 6;</code>
       */
      public Builder setS6Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        s6_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s7_ = "";
      /**
       * <code>required string s7 = 7;</code>
       */
      public boolean hasS7() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string s7 = 7;</code>
       */
      public java.lang.String getS7() {
        java.lang.Object ref = s7_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s7_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s7 = 7;</code>
       */
      public com.google.protobuf.ByteString
          getS7Bytes() {
        java.lang.Object ref = s7_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s7_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s7 = 7;</code>
       */
      public Builder setS7(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        s7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s7 = 7;</code>
       */
      public Builder clearS7() {
        bitField0_ = (bitField0_ & ~0x00000040);
        s7_ = getDefaultInstance().getS7();
        onChanged();
        return this;
      }
      /**
       * <code>required string s7 = 7;</code>
       */
      public Builder setS7Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        s7_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s8_ = "";
      /**
       * <code>required string s8 = 8;</code>
       */
      public boolean hasS8() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string s8 = 8;</code>
       */
      public java.lang.String getS8() {
        java.lang.Object ref = s8_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s8_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s8 = 8;</code>
       */
      public com.google.protobuf.ByteString
          getS8Bytes() {
        java.lang.Object ref = s8_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s8_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s8 = 8;</code>
       */
      public Builder setS8(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        s8_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s8 = 8;</code>
       */
      public Builder clearS8() {
        bitField0_ = (bitField0_ & ~0x00000080);
        s8_ = getDefaultInstance().getS8();
        onChanged();
        return this;
      }
      /**
       * <code>required string s8 = 8;</code>
       */
      public Builder setS8Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        s8_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s9_ = "";
      /**
       * <code>required string s9 = 9;</code>
       */
      public boolean hasS9() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string s9 = 9;</code>
       */
      public java.lang.String getS9() {
        java.lang.Object ref = s9_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s9_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string s9 = 9;</code>
       */
      public com.google.protobuf.ByteString
          getS9Bytes() {
        java.lang.Object ref = s9_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s9_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string s9 = 9;</code>
       */
      public Builder setS9(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        s9_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string s9 = 9;</code>
       */
      public Builder clearS9() {
        bitField0_ = (bitField0_ & ~0x00000100);
        s9_ = getDefaultInstance().getS9();
        onChanged();
        return this;
      }
      /**
       * <code>required string s9 = 9;</code>
       */
      public Builder setS9Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        s9_ = value;
        onChanged();
        return this;
      }

      private int i10_ ;
      /**
       * <code>required int32 i10 = 10;</code>
       */
      public boolean hasI10() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 i10 = 10;</code>
       */
      public int getI10() {
        return i10_;
      }
      /**
       * <code>required int32 i10 = 10;</code>
       */
      public Builder setI10(int value) {
        bitField0_ |= 0x00000200;
        i10_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 i10 = 10;</code>
       */
      public Builder clearI10() {
        bitField0_ = (bitField0_ & ~0x00000200);
        i10_ = 0;
        onChanged();
        return this;
      }

      private int i11_ ;
      /**
       * <code>required int32 i11 = 11;</code>
       */
      public boolean hasI11() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int32 i11 = 11;</code>
       */
      public int getI11() {
        return i11_;
      }
      /**
       * <code>required int32 i11 = 11;</code>
       */
      public Builder setI11(int value) {
        bitField0_ |= 0x00000400;
        i11_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 i11 = 11;</code>
       */
      public Builder clearI11() {
        bitField0_ = (bitField0_ & ~0x00000400);
        i11_ = 0;
        onChanged();
        return this;
      }

      private int i12_ ;
      /**
       * <code>required int32 i12 = 12;</code>
       */
      public boolean hasI12() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int32 i12 = 12;</code>
       */
      public int getI12() {
        return i12_;
      }
      /**
       * <code>required int32 i12 = 12;</code>
       */
      public Builder setI12(int value) {
        bitField0_ |= 0x00000800;
        i12_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 i12 = 12;</code>
       */
      public Builder clearI12() {
        bitField0_ = (bitField0_ & ~0x00000800);
        i12_ = 0;
        onChanged();
        return this;
      }

      private int i13_ ;
      /**
       * <code>required int32 i13 = 13;</code>
       */
      public boolean hasI13() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required int32 i13 = 13;</code>
       */
      public int getI13() {
        return i13_;
      }
      /**
       * <code>required int32 i13 = 13;</code>
       */
      public Builder setI13(int value) {
        bitField0_ |= 0x00001000;
        i13_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 i13 = 13;</code>
       */
      public Builder clearI13() {
        bitField0_ = (bitField0_ & ~0x00001000);
        i13_ = 0;
        onChanged();
        return this;
      }

      private int i14_ ;
      /**
       * <code>required int32 i14 = 14;</code>
       */
      public boolean hasI14() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required int32 i14 = 14;</code>
       */
      public int getI14() {
        return i14_;
      }
      /**
       * <code>required int32 i14 = 14;</code>
       */
      public Builder setI14(int value) {
        bitField0_ |= 0x00002000;
        i14_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 i14 = 14;</code>
       */
      public Builder clearI14() {
        bitField0_ = (bitField0_ & ~0x00002000);
        i14_ = 0;
        onChanged();
        return this;
      }

      private int i15_ ;
      /**
       * <code>required int32 i15 = 15;</code>
       */
      public boolean hasI15() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required int32 i15 = 15;</code>
       */
      public int getI15() {
        return i15_;
      }
      /**
       * <code>required int32 i15 = 15;</code>
       */
      public Builder setI15(int value) {
        bitField0_ |= 0x00004000;
        i15_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 i15 = 15;</code>
       */
      public Builder clearI15() {
        bitField0_ = (bitField0_ & ~0x00004000);
        i15_ = 0;
        onChanged();
        return this;
      }

      private int i16_ ;
      /**
       * <code>required int32 i16 = 16;</code>
       */
      public boolean hasI16() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>required int32 i16 = 16;</code>
       */
      public int getI16() {
        return i16_;
      }
      /**
       * <code>required int32 i16 = 16;</code>
       */
      public Builder setI16(int value) {
        bitField0_ |= 0x00008000;
        i16_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 i16 = 16;</code>
       */
      public Builder clearI16() {
        bitField0_ = (bitField0_ & ~0x00008000);
        i16_ = 0;
        onChanged();
        return this;
      }

      private int i17_ ;
      /**
       * <code>required int32 i17 = 17;</code>
       */
      public boolean hasI17() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>required int32 i17 = 17;</code>
       */
      public int getI17() {
        return i17_;
      }
      /**
       * <code>required int32 i17 = 17;</code>
       */
      public Builder setI17(int value) {
        bitField0_ |= 0x00010000;
        i17_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 i17 = 17;</code>
       */
      public Builder clearI17() {
        bitField0_ = (bitField0_ & ~0x00010000);
        i17_ = 0;
        onChanged();
        return this;
      }

      private int i18_ ;
      /**
       * <code>required int32 i18 = 18;</code>
       */
      public boolean hasI18() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>required int32 i18 = 18;</code>
       */
      public int getI18() {
        return i18_;
      }
      /**
       * <code>required int32 i18 = 18;</code>
       */
      public Builder setI18(int value) {
        bitField0_ |= 0x00020000;
        i18_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 i18 = 18;</code>
       */
      public Builder clearI18() {
        bitField0_ = (bitField0_ & ~0x00020000);
        i18_ = 0;
        onChanged();
        return this;
      }

      private boolean b19_ ;
      /**
       * <code>required bool b19 = 19;</code>
       */
      public boolean hasB19() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <code>required bool b19 = 19;</code>
       */
      public boolean getB19() {
        return b19_;
      }
      /**
       * <code>required bool b19 = 19;</code>
       */
      public Builder setB19(boolean value) {
        bitField0_ |= 0x00040000;
        b19_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool b19 = 19;</code>
       */
      public Builder clearB19() {
        bitField0_ = (bitField0_ & ~0x00040000);
        b19_ = false;
        onChanged();
        return this;
      }

      private boolean b20_ ;
      /**
       * <code>required bool b20 = 20;</code>
       */
      public boolean hasB20() {
        return ((bitField0_ & 0x00080000) == 0x00080000);
      }
      /**
       * <code>required bool b20 = 20;</code>
       */
      public boolean getB20() {
        return b20_;
      }
      /**
       * <code>required bool b20 = 20;</code>
       */
      public Builder setB20(boolean value) {
        bitField0_ |= 0x00080000;
        b20_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool b20 = 20;</code>
       */
      public Builder clearB20() {
        bitField0_ = (bitField0_ & ~0x00080000);
        b20_ = false;
        onChanged();
        return this;
      }

      private boolean b21_ ;
      /**
       * <code>required bool b21 = 21;</code>
       */
      public boolean hasB21() {
        return ((bitField0_ & 0x00100000) == 0x00100000);
      }
      /**
       * <code>required bool b21 = 21;</code>
       */
      public boolean getB21() {
        return b21_;
      }
      /**
       * <code>required bool b21 = 21;</code>
       */
      public Builder setB21(boolean value) {
        bitField0_ |= 0x00100000;
        b21_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool b21 = 21;</code>
       */
      public Builder clearB21() {
        bitField0_ = (bitField0_ & ~0x00100000);
        b21_ = false;
        onChanged();
        return this;
      }

      private boolean b22_ ;
      /**
       * <code>required bool b22 = 22;</code>
       */
      public boolean hasB22() {
        return ((bitField0_ & 0x00200000) == 0x00200000);
      }
      /**
       * <code>required bool b22 = 22;</code>
       */
      public boolean getB22() {
        return b22_;
      }
      /**
       * <code>required bool b22 = 22;</code>
       */
      public Builder setB22(boolean value) {
        bitField0_ |= 0x00200000;
        b22_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool b22 = 22;</code>
       */
      public Builder clearB22() {
        bitField0_ = (bitField0_ & ~0x00200000);
        b22_ = false;
        onChanged();
        return this;
      }

      private boolean b23_ ;
      /**
       * <code>required bool b23 = 23;</code>
       */
      public boolean hasB23() {
        return ((bitField0_ & 0x00400000) == 0x00400000);
      }
      /**
       * <code>required bool b23 = 23;</code>
       */
      public boolean getB23() {
        return b23_;
      }
      /**
       * <code>required bool b23 = 23;</code>
       */
      public Builder setB23(boolean value) {
        bitField0_ |= 0x00400000;
        b23_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool b23 = 23;</code>
       */
      public Builder clearB23() {
        bitField0_ = (bitField0_ & ~0x00400000);
        b23_ = false;
        onChanged();
        return this;
      }

      private boolean b24_ ;
      /**
       * <code>required bool b24 = 24;</code>
       */
      public boolean hasB24() {
        return ((bitField0_ & 0x00800000) == 0x00800000);
      }
      /**
       * <code>required bool b24 = 24;</code>
       */
      public boolean getB24() {
        return b24_;
      }
      /**
       * <code>required bool b24 = 24;</code>
       */
      public Builder setB24(boolean value) {
        bitField0_ |= 0x00800000;
        b24_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool b24 = 24;</code>
       */
      public Builder clearB24() {
        bitField0_ = (bitField0_ & ~0x00800000);
        b24_ = false;
        onChanged();
        return this;
      }

      private boolean b25_ ;
      /**
       * <code>required bool b25 = 25;</code>
       */
      public boolean hasB25() {
        return ((bitField0_ & 0x01000000) == 0x01000000);
      }
      /**
       * <code>required bool b25 = 25;</code>
       */
      public boolean getB25() {
        return b25_;
      }
      /**
       * <code>required bool b25 = 25;</code>
       */
      public Builder setB25(boolean value) {
        bitField0_ |= 0x01000000;
        b25_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool b25 = 25;</code>
       */
      public Builder clearB25() {
        bitField0_ = (bitField0_ & ~0x01000000);
        b25_ = false;
        onChanged();
        return this;
      }

      private boolean b26_ ;
      /**
       * <code>required bool b26 = 26;</code>
       */
      public boolean hasB26() {
        return ((bitField0_ & 0x02000000) == 0x02000000);
      }
      /**
       * <code>required bool b26 = 26;</code>
       */
      public boolean getB26() {
        return b26_;
      }
      /**
       * <code>required bool b26 = 26;</code>
       */
      public Builder setB26(boolean value) {
        bitField0_ |= 0x02000000;
        b26_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool b26 = 26;</code>
       */
      public Builder clearB26() {
        bitField0_ = (bitField0_ & ~0x02000000);
        b26_ = false;
        onChanged();
        return this;
      }

      private boolean b27_ ;
      /**
       * <code>required bool b27 = 27;</code>
       */
      public boolean hasB27() {
        return ((bitField0_ & 0x04000000) == 0x04000000);
      }
      /**
       * <code>required bool b27 = 27;</code>
       */
      public boolean getB27() {
        return b27_;
      }
      /**
       * <code>required bool b27 = 27;</code>
       */
      public Builder setB27(boolean value) {
        bitField0_ |= 0x04000000;
        b27_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool b27 = 27;</code>
       */
      public Builder clearB27() {
        bitField0_ = (bitField0_ & ~0x04000000);
        b27_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x08000000) == 0x08000000)) {
          list_ = new com.google.protobuf.LazyStringArrayList(list_);
          bitField0_ |= 0x08000000;
         }
      }
      /**
       * <code>repeated string list = 28;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getListList() {
        return list_.getUnmodifiableView();
      }
      /**
       * <code>repeated string list = 28;</code>
       */
      public int getListCount() {
        return list_.size();
      }
      /**
       * <code>repeated string list = 28;</code>
       */
      public java.lang.String getList(int index) {
        return list_.get(index);
      }
      /**
       * <code>repeated string list = 28;</code>
       */
      public com.google.protobuf.ByteString
          getListBytes(int index) {
        return list_.getByteString(index);
      }
      /**
       * <code>repeated string list = 28;</code>
       */
      public Builder setList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 28;</code>
       */
      public Builder addList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 28;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<java.lang.String> values) {
        ensureListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, list_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 28;</code>
       */
      public Builder clearList() {
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x08000000);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 28;</code>
       */
      public Builder addListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Products22)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Products22)
    private static final com.cl.java.serialization.compare.Products2.Products22 defaultInstance;static {
      defaultInstance = new com.cl.java.serialization.compare.Products2.Products22();
    }

    public static com.cl.java.serialization.compare.Products2.Products22 getDefaultInstance() {
      return defaultInstance;
    }

    public com.cl.java.serialization.compare.Products2.Products22 getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Products22_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Products22_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\010tutorial\"\360\002\n\nProducts22\022\n\n" +
      "\002s1\030\001 \002(\t\022\n\n\002s2\030\002 \002(\t\022\n\n\002s3\030\003 \002(\t\022\n\n\002s4\030" +
      "\004 \002(\t\022\n\n\002s5\030\005 \002(\t\022\n\n\002s6\030\006 \002(\t\022\n\n\002s7\030\007 \002(" +
      "\t\022\n\n\002s8\030\010 \002(\t\022\n\n\002s9\030\t \002(\t\022\013\n\003i10\030\n \002(\005\022\013" +
      "\n\003i11\030\013 \002(\005\022\013\n\003i12\030\014 \002(\005\022\013\n\003i13\030\r \002(\005\022\013\n" +
      "\003i14\030\016 \002(\005\022\013\n\003i15\030\017 \002(\005\022\013\n\003i16\030\020 \002(\005\022\013\n\003" +
      "i17\030\021 \002(\005\022\013\n\003i18\030\022 \002(\005\022\013\n\003b19\030\023 \002(\010\022\013\n\003b" +
      "20\030\024 \002(\010\022\013\n\003b21\030\025 \002(\010\022\013\n\003b22\030\026 \002(\010\022\013\n\003b2" +
      "3\030\027 \002(\010\022\013\n\003b24\030\030 \002(\010\022\013\n\003b25\030\031 \002(\010\022\013\n\003b26" +
      "\030\032 \002(\010\022\013\n\003b27\030\033 \002(\010\022\014\n\004list\030\034 \003(\tB.\n!com",
      ".cl.java.serialization.compareB\tProducts" +
      "2"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Products22_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Products22_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_Products22_descriptor,
        new java.lang.String[] { "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "I10", "I11", "I12", "I13", "I14", "I15", "I16", "I17", "I18", "B19", "B20", "B21", "B22", "B23", "B24", "B25", "B26", "B27", "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
