spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3307/wyn?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
eureka:
  #注册地址
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/

wyn:
  sid: CHN821
  apiKey: testapi
  apiSecret: testapi
  api:
    baseUrl: http://quickapitest.wyn88.com/
scheduling:
  enable: true


