server:
  port: 8081

#数据库配置
spring:
  profiles:
    active: local
  datasource:
    druid:
      validation-query: SELECT 1 FROM DUAL
      initial-size: 5
      min-idle: 5
      max-active: 500
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.jdbc.Driver
      connection-init-sqls: set names utf8mb4;

  application:
    name: wyn-provider #使用ip进行注册
eureka:
  instance:
    prefer-ip-address: true

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:mapping/**/**.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cl.wyn.core.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type:

logging:
  config: classpath:logback-spring.xml
logging.level.org.springframework.boot.autoconfigure: ERROR
#维也纳api接口
wyn:
  sourceId: "740882764928122880"
  api:
    channel:
      authPath: Channel/Auth
    hotel:
      getModelPath: Hotel/GetModel
      getListPath: Hotel/GetList
      getPicListPath: Hotel/GetPicList
      getRoomTypePath: Hotel/GetRoomType
      getRoomTypePicPath: Hotel/GetRoomTypePic
    room:
        roomStatusPath: Room2/RoomStatus
        roomAvailablePath: Room2/RoomAvailable
        roomAvailableUpPath: Room2/RoomAvailableUp
    city:
        getListPath: City/GetList
        getProvinceCityListPath: City/GetProvinceCityList
    order:
      confirmBookingPath: Order2/ConfirmBooking2
      bookingPath: Order2/Booking2
      getOrderAuditPath: Order2/GetOrderAudit
      getOrderActualCheckInPath: Order2/GetOrderActaulCheckInInfo
      getOrderPath: Order2/GetOrder
      cancelOrderPath: Order2/CancelOrder
#scheduling:
#  enable: false
#  syncData:
#    cron: 0 30 * * * ?
