spring:
  datasource:
    druid:
      url: jdbc:mysql://172.16.15.166:3306/ots_lima_dev_hotel?characterEncoding=UTF-8&allowMultiQueries=true
      username: ots_lima
      password: Ots_lima@123
eureka:
  #注册地址
  client:
    service-url:
      defaultZone: http://172.16.15.150:12003/eureka/
wyn:
  sid: CHN821
  apiKey: testapi
  apiSecret: testapi
  api:
    baseUrl: http://quickapitest.wyn88.com/


