server:
  port: 8090
spring:
  datasource:
    druid:
      url: jdbc:mysql://47.111.15.229:3306/ots_lima_dev_hotel?characterEncoding=UTF-8&allowMultiQueries=true
      username: ots_lima
      password: Ots_lima@123
eureka:
  #注册地址
  client:
    service-url:
      defaultZone: http://127.0.0.1:8002/eureka/
wyn:
  sid: CHN821
  apiKey: testapi
  apiSecret: testapi
  api:
    baseUrl: http://quickapitest.wyn88.com/



